### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by TimWSpence** [permutive-engineering/prometheus4cats#44]
```
==> X prometheus4cats.CounterNameSuite.names must not contain special chars  0.072s munit.FailException: /home/runner/work/prometheus4cats/prometheus4cats/core/src/test/scala/prometheus4cats/NameSuite.scala:52 assertion failed
51:    forAll { (s: String, c: Char) =>
52:      assert(make(s"$c$s$suffix").isLeft)
53:    }

Failing seed: P7tWINyyt1QBPDNHWTxvjOoD_8ovGQz5ezVmmQQFckP=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "P7tWINyyt1QBPDNHWTxvjOoD_8ovGQz5ezVmmQQFckP="

Falsified after 45 passed tests.
> ARG_0: ""
> ARG_1: :
> ARG_0_ORIGINAL: "::wB"
    at munit.FailException.copy(FailException.scala:27)
    at munit.FailException.withMessage(FailException.scala:20)
    at munit.FailException.withMessage(FailException.scala:19)
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:91)
    at munit.ScalaCheckSuite.$init$$$anonfun$2$$anonfun$1$$anonfun$1(ScalaCheckSuite.scala:46)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:475)
    at munit.Suite$$anon$1.execute(Suite.scala:26)
    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
    at scala.concurrent.impl.Promise$DefaultPromise.transform(Promise.scala:128)
    at munit.internal.FutureCompat$ExtensionFuture.transformCompat(FutureCompat.scala:16)
    at munit.ScalaCheckSuite.$init$$$anonfun$3$$anonfun$2(ScalaCheckSuite.scala:48)
    at munit.GenericTest.withBodyMap$$anonfun$1(GenericTest.scala:33)
    at munit.MUnitRunner.$anonfun$8(MUnitRunner.scala:296)
    ```

**Comment by TimWSpence** [comment]
Addressed by https://github.com/permutive-engineering/prometheus4cats/pull/41
